### ISSUE TITLE
Optimize smart contracts storage in chain

### ISSUE THREAD

**Issue by 0xAAE** [CREDITSCOM/node#16]
**The purpose is to keep nearly constant size of every contract in chain**
The contract size in storage may increase due to data expand in its state and may become too large. Currently contract state is duplicated in chain every time when contract is executed. This leads to significant costs in disk space and seems to be inefficient.

**The possible solution is to separate contract state storage from transactions**
The idea is to store last state of every contract outside the chain and put in every execute transaction contract's state hash value

**Comment by Instand** [comment]
Done
