### ISSUE TITLE
Some balance needed for contract execution with 'NewState' set to true

### ISSUE THREAD

**Issue by tkoen93** [CREDITSCOM/node#17]
**Describe the bug**
To request the current state of a contract it's possible to initiate a transaction and set the `NewState` parameter to `true`. Those transactions need to be signed by a valid keypair, but will not go into the consensus protocol if I'm not mistaken. That means that there is no fee that needs to be paid.

I experienced the following issue: while creating a transaction with an empty wallet and `NewState` set to `true`, the return message I receive mentions the following:
`max fee is not enough, counted fee will be 0.000482`

That message makes sense, only if I set `NewState` to `false`. As I don't have to pay any fee with this transaction it looks incorrect to me.

**To Reproduce**
- Create new wallet, don't put any balance in it
- Pick a random smart contract that contains some functions
- Initiate a transaction to that contract with `NewState` set to `true`

**Expected behavior**
Returning the requested value instead of showing this error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/43822286/59034076-8a513700-886a-11e9-8620-b238861fee60.png)

**Comment by botstorm** [comment]
The Flag NewState=true asks the node not to send transactions, but to perform the specified method specified by the target key of the smart contract

The fix you specified will be in the next updates.

**Comment by tkoen93** [comment]
Works perfect in testnet v4.2.417. Thanks!
