### ISSUE TITLE
Incorrect consensus

### ISSUE THREAD

**Issue by CryptoUser88** [CREDITSCOM/node#18]
A node that does not have a 50,000 CS account participates in a consensus and receives a commission. 
Testnet 4.2.416.0
https://monitor.credits.com/testnet-r4_2/Account/L5arZyKgzaYLDWy5GKSPTjzvqjMi4uWHAqbiGnjPiFJ

**Comment by botstorm** [comment]
People participated in the consensus until the monitor showed 10k blocks, it was introduced to have time to send CS to the nodes that supported the network. Stacking works
