### ISSUE TITLE
Linux Node - Ability to display the client version under command line

### ISSUE THREAD

**Issue by Toki1975** [CREDITSCOM/node#19]
An interesting feature who can be added is the ability of check the client version under linux command line.

For example, adding the -v or --version argument to the command line.
This feature could be also useful with the windows client node under command line.

**Comment by kondrashovsv** [comment]
You are right, this feature will be implemented 👍

**Comment by DmitriyYashenko** [comment]
build after https://github.com/CREDITSCOM/node/commit/fb8e0126f2cfcf54daaa2116f7834a8dd915847c  ./client --version

**Comment by DmitriyYashenko** [comment]
The functionality is added in the last commit, rebuild the node and check with the command ```./client --version```

**Comment by DmitriyYashenko** [comment]
The functionality is added in the last commit, rebuild the node and check with the command 
```./client --version```

**Comment by Toki1975** [comment]
Hi Dimitry, Thanks to Timo from the private group who has rebuilt the node. We are able now to see the node version under linux. 
![2019-06-11_140427](https://user-images.githubusercontent.com/50962779/59270643-46877480-8c52-11e9-92ef-9d526766912a.png)


Best regards.
