### ISSUE TITLE
Node Encryption explanations

### ISSUE THREAD

**Issue by Toki1975** [CREDITSCOM/node#21]
When we start a node (Linux or windows, we have the possibility to encrypt the key. ( Option 1 recommended)

I have 2 questions related to the encryption ( see print screen below)

1. How can we use the Phrase on 24 words generated in case losing both public and private key.
2. How can we use the the option "to use file file press F"

A word of explanations is really needed to allow us to update the vps/linux/installation guide.

Best regards,

Toki1975

![2019-06-07_112222](https://user-images.githubusercontent.com/50962779/59102399-39097c00-892c-11e9-8d73-5fb7987b7998.png)
[v2-how-to-run-a-credits-node-on-a-pc-or-on-a-linux-vps.pdf](https://github.com/CREDITSCOM/node/files/3265742/v2-how-to-run-a-credits-node-on-a-pc-or-on-a-linux-vps.pdf)

**Comment by DmitriyYashenko** [comment]
https://github.com/CREDITSCOM/node/wiki/Deterministic-key-generation-cscrypto

**Comment by Toki1975** [comment]
Hi Dimitry,

No worries. I know Team have a lot to do. I have read your documentation but there is still one question.
What contain  the file /home/user/test.*** ?

**From your documentation:**
_To use password for encryption/decryption press "p", to use file press "f": f
Enter path to file (will be used as cipher key):home/user/test.***_

For the rest it is clearly explained and will help a lot.

Regards.

**Comment by CryptoDZ** [comment]
![issu](https://user-images.githubusercontent.com/51496158/59136408-4ef65b80-8983-11e9-8437-0507c2096e1c.jpg)
Hello DmitriyYashenko thank you for sharing the documentation, it is appreciable.
it seems to me that my procedure is correct, it generates an error code that I tested with several types of files

**Comment by DmitriyYashenko** [comment]
functionality has been fixed https://github.com/CREDITSCOM/node/commit/b6b9ddd22025d3d92ffd85711478c1700e81a17d, please ```git pull``` and rebuild the client

**Comment by Toki1975** [comment]
Hi Dimitry, Client has been rebuilt. 
What should we write in the file (for example) : test.txt
Enter path to file (will be used as cipher key):home/user/test.***


Best regards.

**Comment by DmitriyYashenko** [comment]
anything, it can be at least a video file, at least music, whatever you want

**Comment by CryptoDZ** [comment]
> 
> 
> anything, it can be at least a video file, at least music, whatever you want

very ingenious more secure than the current password may be better to add letters in addition to the number to strengthen for example: 2ap9s7 instead of 4 digits

**Comment by DmitriyYashenko** [comment]
You cannot change the password or encryption file until you enter the password or specify the path to the file. Only after entering and restoring the keys will you be asked to dare to encrypt. The command ```./client --dumpkeys my Node1.json``` also trusts the password or the encryption file that you can store, say, on a flash drive or remote storage. Thus, an attacker needs to know your password or have an encryption file to access your keys. A little later, I will try today, we will publish a detailed description of file encryption.

**Comment by DmitriyYashenko** [comment]
You cannot change the password or encryption file until you enter the password or specify the path to the file. Only after entering and restoring the keys will you be asked to dare to encrypt. The command ```./client --dumpkeys my Node1.json``` also trusts the password or the encryption file that you can store, say, on a flash drive or remote storage. Thus, an attacker needs to know your password or have an encryption file to access your keys. A little later, I will try today, we will publish a detailed description of file encryption.

**Comment by DmitriyYashenko** [comment]
You cannot change the password or encryption file until you enter the password or specify the path to the file. Only after entering and restoring the keys will you be asked to dare to encrypt. The command ```./client --dumpkeys my Node1.json``` also trusts the password or the encryption file that you can store, say, on a flash drive or remote storage. Thus, an attacker needs to know your password or have an encryption file to access your keys. A little later, I will try today, we will publish a detailed description of file encryption.

**Comment by DmitriyYashenko** [comment]
You cannot change the password or encryption file until you enter the password or specify the path to the file. Only after entering and restoring the keys will you be asked to dare to encrypt. The command ```./client --dumpkeys my Node1.json``` also trusts the password or the encryption file that you can store, say, on a flash drive or remote storage. Thus, an attacker needs to know your password or have an encryption file to access your keys. A little later, I will try today, we will publish a detailed description of file encryption.

**Comment by DmitriyYashenko** [comment]
You cannot change the password or encryption file until you enter the password or specify the path to the file. Only after entering and restoring the keys will you be asked to dare to encrypt. The command ./client --dumpkeys my Node1.json also trusts the password or the encryption file that you can store, say, on a flash drive or remote storage. Thus, an attacker needs to know your password or have an encryption file to access your keys. A little later, I will try today, we will publish a detailed description of file encryption.

**Comment by DmitriyYashenko** [comment]
You cannot change the password or encryption file until you enter the password or specify the path to the file. Only after entering and restoring the keys will you be asked to dare to encrypt. The command ```./client --dumpkeys my Node1.json``` also trusts the password or the encryption file that you can store, say, on a flash drive or remote storage. Thus, an attacker needs to know your password or have an encryption file to access your keys. A little later, I will try today, we will publish a detailed description of file encryption.

**Comment by DmitriyYashenko** [comment]
Detailed description of the file encryption algorithm at the end of the document https://github.com/CREDITSCOM/node/wiki/Deterministic-key-generation-cscrypto
