### ISSUE TITLE
Difference in total fee (network node list) and actual received fee 

### ISSUE THREAD

**Issue by tkoen93** [CREDITSCOM/node#26]
**Describe the bug**
It's possible to view the total fee received by a node on the network node list page. The fees displayed on this page are a bit off compared to what's received in the wallet.

This bug is present in tesnet 4.2.417.

**To Reproduce**
- Check any node on the network nodes pages to see the 'total fee' according to that page.
- Check the wallet balance, subtract the initial transaction. Amounts should be the same, which is not.

**Screenshot**
As an example:
![image](https://user-images.githubusercontent.com/43822286/59560503-47822280-9013-11e9-8d99-41b36f779386.png)
![image](https://user-images.githubusercontent.com/43822286/59560508-57016b80-9013-11e9-8964-6e8aa79bf3c6.png)

**Comment by kondrashovsv** [comment]
This problem was associated with incorrect display of the commission. In the near future, a new version will be published in testnet, correcting the error

**Comment by Instand** [comment]
Done
