### ISSUE TITLE
Error Node on Linux 

### ISSUE THREAD

**Issue by CryptoDZ** [CREDITSCOM/node#29]
Hi 
same errors after i selected "q" to exit or after choosing "p" then i pressed "enter" instead of password
![Sans titre 2](https://user-images.githubusercontent.com/51496158/59631616-8f569600-9148-11e9-88e5-ca0487b809cb.jpg)

**Comment by DmitriyYashenko** [comment]
please send a screen with files folder and a config file

**Comment by CryptoDZ** [comment]
[params]
node_type=client
bootstrap_type=signal_server
ipv6=false

[signal_server]
ip=169.38.89.216
port=6018

[host_input]
port=6000

[api]
;port=9090
;executor_port=9080
apiexec_port=9070
;ajax_port=8081

[Core]
Filter="%Severity% >= debug"

[Sinks.Console]
Destination=Console
Filter="%Severity% >= info"

[Sinks.File]
Destination=TextFile
Target="log"
MaxFiles=4
RotationSize=52428800
AutoFlush=true
FileName="log/log_%N.txt"
Filter="%Severity% >= trace"
Format="[%TimeStamp%] [%ThreadID%] [%Severity%] %Message%"

-----------------------------
don't be surprised by the massage which indicates it "don't found the keys" I have removed these files I just forgot to put them before launching the node again

[0x00007fb85192d7c0] [error] only occurs if you click enter instead of putting the password

**Comment by DmitriyYashenko** [comment]
Hello, we managed to reproduce this error, the developers were given the task of correcting

**Comment by CryptoDZ** [comment]
Great! thanks for the follow up ;)
