### ISSUE TITLE
Memory leak Linux Client node Testnet version 4.2.412.4 

### ISSUE THREAD

**Issue by Toki1975** [CREDITSCOM/node#3]
**Describe the bug**
Used amount of memory used by Linux client is not stable/regular. 

The amount of memory used by the client node is increasing little by little. After starting the node the memory level used is about 800mb, but after a few days as you can see in the attached log file, client use more than 3GB of memory. Which could crash / make unstable the system if the maximum available memory level available is reached.

The attached log file was generated with the following command that checks every minute the amount of memory used by the specified process:

**watch -n 60 "pmap -x 5648 | grep total >> /home/credits/Clientmemory_20190516_0844PM.txt"**

Where the number **5648** is the PID of the node client process

PID of the node client process is know by the following command:

**ps -ef | grep client** 

The log file containing 8613 lines, which represents
8613 minutes or 5 days, 23 hours and 33 minutes.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 18.04

[ClientMemory_20190517_0720PM.txt](https://github.com/CREDITSCOM/node/files/3213385/ClientMemory_20190517_0720PM.txt)

**Comment by ksv81** [comment]
the issue is closed, so a similar question on the new version of the release #10
