### ISSUE TITLE
Build failure: thrift Haskell library

### ISSUE THREAD

**Issue by dkasak** [CREDITSCOM/node#40]
The Haskell library for Thrift fails to build due to the following error

```
src/Thrift/Transport/Handle.hs:34:1: error:
    Could not find module ‘Network’
    Use -v to see a list of the files searched for.
   |
34 | import Network
   | ^^^^^^^^^^^^^^
```
This is because in the `Network` module was [deprecated in network-2.7](https://github.com/haskell/network#27) and [removed in network-3.0](https://github.com/haskell/network#30). However, the cabal file for it specifies it needs `network > 2.6`.

I realize this is a third-party module. Is the Thrift Haskell library necessary for the functioning of the CREDITSCOM node, though? If not, is there an easy way of disabling it?

This is on Arch Linux using GHC 8.6.5.

**Comment by DmitriyYashenko** [comment]
Hello, try this solution https://github.com/apache/thrift/pull/1780/commits/758024b9b32149e22468f0dd484f447cc4e0181c
