### ISSUE TITLE
выход за пределы массива

### ISSUE THREAD

**Issue by alexeyneu** [CREDITSCOM/node#41]
**Describe the bug**

**To Reproduce**
использовать limit на максисмум и ненулевой offset

**Expected behavior**
ничего хорошего

**Screenshots**

**Desktop (please complete the following information):**
любая

**Smartphone (please complete the following information):**
любой

**Additional context**
https://github.com/CREDITSCOM/node/blob/9dfff31f705a3e5fbec9508ea64c6b721bea1bcb/api/src/apihandler.cpp#L508-L510  
эти вещи code analyzer схватывает вроди. в msvc team edition он был

**Comment by alexeyneu** [comment]
`transactionsCount -= offset;`  
неграмотное использование

**Comment by botstorm** [comment]
@alexeyneu Please use english language
