### ISSUE TITLE
Testnet v4.2.420 - frequent lost of communication to signal server

### ISSUE THREAD

**Issue by pnb69** [CREDITSCOM/node#50]
Last two days my node experienced problems with connection to signal server
after 1-2 hours of proper work. It happened several times
during this times and always terminating client.exe (Ctrl+C) and
restarting the node helped to bring proper work back.
Maybe I'm wrong but I fill it is associated with extensive execution of smart contracts
causing problems in testnet network. Probably another tester was trying to reproduce
another bug with smart contracts. Now I see smart contracts are executed
quite seldom and my node is working for few hours without problems.
I did a ping to signal server during these problems with following results:
    time=27ms
    TTL=116
    0% loss

System: Windows 10 Pro

Please find log file from my node attached

[log_1.txt](https://github.com/CREDITSCOM/node/files/3431333/log_1.txt)

**Comment by 13fredom13** [comment]
Thank you, we are working on a solution to this problem. There are no problems with connection to signal server. Node hangs in an infinite loop and can only connect to the signal server
