### ISSUE TITLE
Node-client on Ubuntu 16.04 can Not be started/launched

### ISSUE THREAD

**Issue by angelesmanzo** [CREDITSCOM/node#6]
An issue was gotten when I was trying to start/launch a new node-client (desktop version for Linux).

Here the steps performed for installing:
1. OS Ubuntu-16.04.6-desktop-amd64 image was installed
2. Oracle Java 11 was installed from PPA repository
3. Client version for Linux was downloaded from credits site: https://credits.com/Content/file_users/Credits_Node_linux_x64_ver_4.2.412.3_test.tar.gz
4. Tar file was unziped in Desktop directory.

Afterward, the client should be launched, the new public key should be created and the node should establish connection to tesnet credits blockchain. However, the following error is showed on the prompt (please see screenshot):

![issue](https://user-images.githubusercontent.com/22745892/58314484-41d05d00-7e18-11e9-8de4-2b3ef465eb40.PNG)

Additional comment: It seems that some dependencies/packages are missing and should be included/installed for Ubuntu: libstdc++6 and libc6. 

The same issue is gotten by launching the desktop client for credits blockchain MainNet

Big thanks for support!

Angeles

**Comment by tkoen93** [comment]
To verify if it's missing you should be able to use the following commands.

`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI`
`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`
`strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC`

I've heard before that these issues exist on 16.04, but they don't exist on 18.04. So best thing you can probably do is update them (or update to Ubuntu 18.04).

Regarding the first two, you might want to take a look over here: https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

Regarding libc.s0.6 you can try the solution as mentioned over here: https://askubuntu.com/questions/736208/upgrading-glibc

I have no idea if this will work, but as you're missing the needed version it seems logical to me to update them.

**Comment by angelesmanzo** [comment]
I updated OS to Ubuntu 18.04 (Bionic Beaver). All is Ok! node-client was properly launched and it connected to Credits Blockchain.
Big thannks for the help!
Angeles
