### ISSUE TITLE
Self build client can not connect to signal server.

### ISSUE THREAD

**Issue by tkoen93** [CREDITSCOM/node#7]
**Describe the bug**
Managed to build the node from the code available on github. Upon starting the node it tries to connect to the signal server, but nothing happens with that. I simply replaced the client file with the client file I built, so that the config.ini should work.

Something I noticed is that the client file is about 15% of the file provided on the developers portal. See the image below.
![image](https://user-images.githubusercontent.com/43822286/58410027-9cb0c100-8071-11e9-9f65-80c1c070690b.png)

The entire `build` folder is about the size of the client file provided by the Credits team. Am I missing any command to finish the build?

I've attached two files `cmake` and `make` as that was the output of running those commands.
[cmake.log](https://github.com/CREDITSCOM/node/files/3223246/cmake.log)
[make.log](https://github.com/CREDITSCOM/node/files/3223235/make.log)

**To Reproduce**
I've used the steps provided in the readme.MD to build the node.

> git clone https://github.com/CREDITSCOM/node.git
cd node
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)

**Comment by micmac0** [comment]
again same here :).
Also I wonder if we can not connect is related to the build version number ? Should we build from a special commit on git ? And last is a suggestion to tag the build you will push on testnet and mainet to help to find the exact commit to build.

**Comment by DmitriyYashenko** [comment]
You have collected a new version of the client, currently only compatible with CreditsNetwork.The update TestNet will be in a few days.

**Comment by tkoen93** [comment]
@DmitriyYashenko can confirm that it works. Thank you. Only keeps me wondering why there is such a difference in size of the client files?!

**Comment by DmitriyYashenko** [comment]
Confirm as soon as TestNet is update. There is no difference in the files, only in the version number. So that the nodes with the old protocol could not break the network.

**Comment by DmitriyYashenko** [comment]
Hello, you can build a branch ```dev``` and check the connection to the testnet

**Comment by tkoen93** [comment]
@DmitriyYashenko Works, thanks.. Still wondering why the client I build is only about 10-15% in size compared to the client that's available on the developers portal.

**Comment by tkoen93** [comment]
Correction, it worked previously (some days ago).

Tried to build the client again (dev branch) and got this error at 90%

![image](https://user-images.githubusercontent.com/43822286/59206266-dec72000-8ba4-11e9-8f73-217abea2abf4.png)

**Comment by DmitriyYashenko** [comment]
After yesterday's fixes there was a compilation error on g ++ compilers. Fixed https://github.com/CREDITSCOM/node/commit/a40dffa59db5c672e35ac2a58c2b0e277d10c949. Please follow the next set of instructions: 
```
///go to the root build folder
git pull
cd build
make
```

**Comment by micmac0** [comment]
thank you seems to work for me with commit : 48fba60a  :+1: 

also :
./client --version
[2019-06-11 10:43:33.242887] [0x00007f19e75bb7c0] [info]    Node version is 416

**Comment by tkoen93** [comment]
Works, thanks! Will close this issue as it's solved.
