### ISSUE TITLE
Credits Desktop Wallet can't be launched - OS Ubuntu 18.04

### ISSUE THREAD

**Issue by angelesmanzo** [CREDITSCOM/node#8]
After starting the node, this new client can't connect to Credits blockchain. Besides the Credits Wallet GUI interface can Not be launched.

The following steps were performed:
1. Oracle Java  was installed from Linux Uprising Java PPA repository according to this:
sudo add-apt-repository ppa:linuxuprising/java
sudo apt update
sudo apt install oracle-java11-installer
sudo apt install oracle-java11-set-default

2. The archive, Credits_Node_Linux_x64_ver_4.2.412.3_test.tar.gz, was downloaded from: https://developers.credits.com/en/Articles/Releases
3. The node was launched by typing on the prompt: "./client"
4. The Keys were generated by entering a password.
5. The executor was launched also: java -jar contract-executor.jar

After launching the node, it should be able to connect to Credits blockchain and the GUI Desktop wallet should be launched. (I tried for TestNet and MainNet)

Please see the screenshot:
![issue 2 mainNet](https://user-images.githubusercontent.com/22745892/58415830-5f0b6280-8088-11e9-997a-ee9a79da9b8d.PNG)

The current OS is Ubuntu 18.04 Bionic Beaver 
 
Thank you in advace for the support!

**Comment by micmac0** [comment]
Hello can you please show the result of :
java -version 
because if you re using oracle jvm, javafx should be included. Also you can use openjdk 11 and follow instructions in the README : https://github.com/CREDITSCOM/ewa

**Comment by angelesmanzo** [comment]
This is the Oracle Java version installed.: 11.0.2.  

![Version Java 11](https://user-images.githubusercontent.com/22745892/58628047-62e5f180-82e1-11e9-8990-75b9f1f8d37e.PNG)

**Comment by micmac0** [comment]
OK anyway looks like your problem is related to javafx missing lib.
As describe at the end of this README : https://github.com/CREDITSCOM/ewa
you can download javafx here : https://gluonhq.com/products/javafx/
Install it somewhere than launch wallet like this example :

```java --module-path=/srv/javafx-sdk-11.0.2/lib --add-modules=javafx.controls,javafx.fxml,javafx.graphics -jar wallet-desktop.jar ``` (replace what follow module-path with the path where you install openjfx (with lib subfolder)
Also do not forget to change settings.properties file to set IP with the IP of your node

**Comment by angelesmanzo** [comment]
Good day!
Thanks for the support. Now, with JavaFX -sdk-11 in root directory src/ wallet was launched! Here, the screenshot.

![Linux Wallet](https://user-images.githubusercontent.com/22745892/58882815-d9219400-86e5-11e9-9266-02d0d1a6ceb0.PNG)
